on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Changelog
    steps:
      - name: Set Version
        run: echo ::set-env name=VERSION::1.1.1
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v1
      - name: Changelog
        id: changelog
        uses: actions/jira-changelog@v1
        with:
          jira_host: 'vultara.atlassian.net'
          jira_email: 'majid.rehman@vultara.com'
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_base_url: 'https://vultara.atlassian.net'
          source_control_range_from: 'release-automation'
          source_control_range_to: 'main'
      - name: Get the changelog message
        run: echo "${{ steps.changelog.outputs.changelog_message }}"